services:
  - type: web
    name: parking-lot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    releaseCommand: "flask db upgrade"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"  